<?php
/**
 * @file
 * Code for the Multistream feature.
 */

include_once 'multistream.features.inc';

define('PLAYER_MAX_DEFAULT', 4);
define('PLAYER_MAX_NOW_PLAYING', 5);

function multistream_menu() {
	$items['multistream'] = array(
			'page callback' => 'multistream_view_multistream',
			'page arguments' => array('queue'),
			'load arguments' => array(),
			'access callback' => true,
			'title' => 'Riot Player',
	);
	$items['multistream/%'] = array(
			'page callback' => 'multistream_view_multistream',
			'page arguments' => array('chain'),
			'access callback' => true,
			'title' => 'Riot Player',
			'type' => MENU_CALLBACK,
	);
	$items['game/autocomplete'] = array(
			'title' => 'Autocomplete Game',
			'page callback' => 'multistream_autocomplete_game',
			'access arguments' => array('access content'),
			'type' => MENU_CALLBACK,
	);	
	$items['my-multistreams/autocomplete'] = array(
			'title' => 'Autocomplete My Multistreams',
			'page callback' => 'multistream_autocomplete_my_multistreams',
			'access arguments' => array('access content'),
			'type' => MENU_CALLBACK,
	);
	$items['multistream/ajax/manage/%'] = array(
	    'title' => 'Multistream Manager',
	    'page callback' => 'multistream_ajax_manage_form',
	    'page arguments' => array(3),
	    'access arguments' => array('access content'),
	    'type' => MENU_CALLBACK,
	);
	$items['multistream/ajax/favorites'] = array(
	    'title' => 'Multistream Favorites',
	    'page callback' => 'multistream_ajax_favorites',
	    'access arguments' => array('access content'),
	    'type' => MENU_CALLBACK,
	);	
	$items['multistream/stream-autocomplete'] = array(
	    'title' => 'Add Stream Autocomplete',
	    'page callback' => 'multistream_autocomplete_stream',
	    'access arguments' => array('access content'),
	    'type' => MENU_CALLBACK,
	);
	$items['multistream/update-streams'] = array(
	    'title' => 'Update Stream',
	    'page callback' => 'multistream_ajax_update_streams',
	    'access arguments' => array('access content'),
	    'type' => MENU_CALLBACK,
	);			
	return $items; 
}

function multistream_ajax_update_streams() {
  global $user;
  
  $values = $_POST;
  
  if(!$node = node_load($values['nid'])) {
    return;
  }
  
  if($node->type != 'multistream') {
    return;
  }
  
  if(!node_access('update', $node)) {
    return false;
  }
  
  $node->field_streams['und'] = array();
  
  foreach($values['streams'] as $stream) {
    if(!is_numeric($stream['stream_id'])) {
      continue;
    }
    $node->field_streams['und'][]['target_id'] = $stream['stream_id'];  
  }
  node_save($node);
  return true;
}

function multistream_view_multistream($context, $streams = array(), $node = null, $streams_collapsed = false, $chat_collapsed = false) {
	drupal_add_library('system', 'drupal.ajax');
	drupal_add_library('system', 'drupal.autocomplete');
	drupal_add_library('system', 'effects.blind');
	drupal_add_library('system', 'ui.sortable');
	
	drupal_add_css(drupal_get_path('module', 'stream').'/css/stream.css');
	drupal_add_js(drupal_get_path('module', 'stream').'/js/stream.js');

	drupal_add_css(drupal_get_path('module', 'multistream').'/css/multistream.css');
	drupal_add_js(drupal_get_path('module', 'multistream').'/js/multistream.js');
	

		
	// Depending on the context, the streams source will be different
	switch($context) {
		case 'queue':
			// Streams will come from the user's $_SESSION
			
			break;
		case 'chain':
			// Streams will come from the path
			// Get args and loop through each to load
			$streams = multistream_get_streams_from_url();

			break;
		case 'riot':
			// Streams will be passed through the $streams array	
			break;
	}
	
	// Order the streams
	$streams = multistream_sort_riot_streams($streams);
		
	multistream_cache_streams($streams);
	
	$vars['streams'] = $streams;
	
	// Load quicktabs both left and right
	$player_menu = module_invoke('panels_mini', 'block_view', 'player_menu');
	$vars['player_menu'] = $player_menu['content'];
	
	$social_menu = module_invoke('panels_mini', 'block_view', 'social_menu');
	$vars['social_menu'] = $social_menu['content'];
	
	$vars['riot'] = multistream_view_player($streams);

	$vars['background'] = '';
	
	if($node) {
	  $background = field_view_field('node', $node, 'field_player_background', 'full');
	  $background[0]['#item']['height'] = null;
	  $background = field_get_items('node', $node, 'field_player_background');
	  if(count($background)) {
	    $vars['background'] = file_create_url($background[0]['uri']);
	  }
	}
	return theme('multistream_view_multistream', $vars);
}

function multistream_get_streams_from_url() {
	$url = $_GET['q'];
	
	// Make sure we have the correct url
	if(!$args = explode('/', $url)) {
		return;
	}
	
	if($args[0] != 'multistream') {
		return;
	}
	
	$streams = array();
	
	array_shift($args);
	
	foreach($args as $channel) {
		if(!$stream = stream_load_stream_by_channel($channel)) {
			continue;
		}
		
		$streams[] = $stream;
	}
	
	return $streams;
}

function multistream_cache_streams($cache = array()) {
	//use cache
	$streams = &drupal_static(__FUNCTION__);

	if (!isset($streams)) {
		$streams = $cache;
	}
	
	return $streams;
}

function multistream_view_player($streams) {
	global $base_url;
	global $conf;
	$settings = array();
	
	if(!is_array($streams)) {
		$streams = array();
	}

	$player = $base_url . variable_get('multistream_player_src', '/StreamRiotPlayer_v1_9.swf');

	$scale = 645 / 836;
	$width = 836 * $scale;
	$height = 600;
	$width = 570;
	if(!variable_get('disable_riot_player', 1)) {
		drupal_add_js(drupal_get_path('module', 'multistream').'/lib/swfobject/src/swfobject.js');
		$script = 'var flashvars = {};var params = {allowScriptAccess: "always", allowFullScreen: "true", allowNetworking: "all", wmode: "transparent"};var attributes = {};';
		$script .= 'swfobject.embedSWF("'.$player.'", "riot-player", "'.$width.'", "'.$height.'", "9.0.0", "expressInstall.swf", flashvars, params, attributes)';
		$settings['multistream']['debug'] = false;
	} else {
	  $settings['multistream']['debug'] = true;
	}

	$count = 0;


	for($i=1;$i<=PLAYER_MAX_NOW_PLAYING;$i++) {
	  $settings['multistream']['stream_pos'][$i] = '';	  
	}
	$settings['multistream']['streams'] = array();
	$settings['multistream']['updated'] = false;
	
	foreach($streams as $key => $stream) {
		$count++;
		
		if($count <= PLAYER_MAX_DEFAULT) {
		  $pos = $count;
  		$settings['multistream']['stream_pos'][$count] = $stream->stream_id;
		} else {
		  $pos = 'q';		   
		}
		
		$settings['multistream']['streams'][$stream->stream_id] = stream_get_stream_settings($stream, $pos);
		
	}

	$default_num = $count <= PLAYER_MAX_DEFAULT ? $count : PLAYER_MAX_DEFAULT;

	$settings['multistream']['num_players'] = $default_num;

	drupal_add_js($settings, 'setting', 'footer', false, true, false);

	return '<div id="riot-player"><div class="no-flash"></div></div>';
}

function multistream_block_info() {
	// This example comes from node.module.
	$blocks['now_playing'] = array(
			'info' => t('Multistream: Now Playing'),
			'cache' => DRUPAL_NO_CACHE,
	);

	$blocks['browse_by_game'] = array(
			'info' => t('Browse by Game'),
			'cache' => DRUPAL_CACHE_GLOBAL,
	);

	$blocks['multistream_browse_results'] = array(
	    'info' => t('Browse Results'),
	    'cache' => DRUPAL_CACHE_GLOBAL,
	);
	
	
	$blocks['multistream_manage'] = array(
			'info' => t('Multistream Manage'),
			'cache' => DRUPAL_NO_CACHE,
	);

	$blocks['multistream_add_channel'] = array(
			'info' => t('Multistream Add Channel'),
			'cache' => DRUPAL_CACHE_GLOBAL,
	);

	$blocks['multistream_panel_actions'] = array(
	    'info' => t('Multistream Panel Actions'),
	    'cache' => DRUPAL_CACHE_GLOBAL,
	);

	$blocks['multistream_panel_actions_anon'] = array(
	    'info' => t('Multistream Panel Actions Anon'),
	    'cache' => DRUPAL_CACHE_GLOBAL,
	);
	$blocks['multistream_twitter_feed'] = array(
	    'info' => t('Multistream Twitter Feed'),
	    'cache' => DRUPAL_CACHE_GLOBAL,
	);	

	$blocks['multistream_chat'] = array(
	    'info' => t('Multistream Chat'),
	    'cache' => DRUPAL_CACHE_GLOBAL,
	);	
	return $blocks;
}

function multistream_block_view($delta = '') {
	// This example is adapted from node.module.
	$block = array();

	switch ($delta) {
		case 'now_playing':
			// Grab the streams from static cache that's loaded in
			// multistream_view_player()
			$streams = multistream_cache_streams();
			
			//drupal_add_js('misc/jquery.form.js');
			drupal_add_library('system', 'drupal.ajax');

			$block['subject'] = t('Now Playing');
			$block['content'] = array(
					'#theme' => 'multistream_now_playing',
					'#title' => t('Now Playing'),
					'#streams' => $streams,
			);
			break;
		case 'browse_by_game':
			$block['subject'] = t('Browse');
			$block['content'] = drupal_render(drupal_get_form('multistream_form_browse_by_game'));
			break;
		case 'multistream_manage':
			$block['subject'] = t('Customize Your Multistreams');
			$block['content'] = drupal_render(multistream_form_manage());				
			break;
		case 'multistream_add_channel':
			$block['subject'] = t('Add Channel');
			$block['content'] = drupal_render(drupal_get_form('multistream_form_add_channel'));				
			break;
		case 'multistream_panel_actions':
		case 'multistream_panel_actions_anon':
		  
		  $block['subject'] = t('Actions');

		  $flag_link = 'Fav';
		  
		  if(user_is_logged_in()) {
  		  if($node = menu_get_object()) {
  		    $flag_link = flag_create_link('multistream_favs', $node->nid);		    
  		  }
		  }
		  		  
		  $links = array(
		  	array('data' => 'Open', 'class'=>array('open')),
		    array('data' => 'New', 'class'=>array('new')),
		    array('data' => $flag_link, 'class'=>array('fav nopopup')),		      
		    array('data' => 'Save', 'class'=>array('save')),
		  );
		  
		  $vars['items'] = $links;
		  $vars['attributes'] = array('class'=>'panel-actions');
		  if($delta == 'multistream_panel_actions_anon') {
		    $vars['attributes']['class'] .= ' anon';
		  }
		  $output = '<div class="panel-actions-wrapper">';
		  $output .= theme('item_list', $vars);
		  
		  $nodes = sr_core_get_entities('multistream', 'owned');
		  
		  $links = array(
		      array('data' => drupal_render(node_view_multiple($nodes, 'selection')), 'class'=>array('open')),
		      array('data' => drupal_render(drupal_get_form('multistream_form_new_multistream')), 'class'=>array('new')),
		      array('data' => 'Fav', 'class'=>array('fav')),
		      array('data' => drupal_render(drupal_get_form('multistream_form_new_multistream', true)), 'class'=>array('save')),
		  );
		  
		  $vars['items'] = $links;
		  $vars['attributes'] = array('class'=>'panel-actions-popup');
		  
		  $output .= theme('item_list', $vars);
      $output .= '</div>';
      		  
      $block['content'] = $output;

		  
		  break;
		  
		case 'multistream_browse_results' :
		  $block['subject'] = t('Results');
		  $block['content'] = '<div id="browse-results"></div>';
		  break;
		case 'multistream_twitter_feed':
		  $block['subject'] = t('Twitter Feed');
		  $node = menu_get_object();
		  
		  $block['content'] = multistream_block_twitter_feed($node);
	    break;	  
    case 'multistream_chat':
      $block['subject'] = t('');
      $block['content'] = multistream_block_chat();
      break;
	}
	return $block;
}

function multistream_block_chat() {
  $streams = multistream_cache_streams();
  
  $output = '<div id="chat-wrapper">';
  $output .= '<div id="chat-open">Open Chat</div>';
  $output .= '<div id="chat-selection">';
  foreach($streams as $stream) {
    $output .= '<div class="stream" data-id="'.$stream->stream_id.'">'.$stream->channel.'</div>';
  }
  $output .= '</div>'; // chat-selection
  $output .= '<div id="chat-rooms"></div>';
  $output .= '</div>'; // chat-wrapper

  return $output;
}

function multistream_block_twitter_feed($node = null) {
  $default = "streamriot";
  $tweets = null;
  $update = null;
  
  if(!$node) {
    $search = $default;
  } else {
    // load cached statuses
    // cache min life 30 seconds
    $result = db_query('SELECT * FROM {multistream_twitter_feeds} WHERE nid = ' . $node->nid)->fetchAssoc();
    if(!empty($result)) {
      $time = time() - 30;
      $update = true;      
      if($result['updated'] >= $time) {
        $tweets = unserialize($result['data']);
      }
    }
    
    
    $feeds = field_get_items('node', $node, 'field_twitter_feed');
    if(empty($feeds)) {
      $search = $default;
    } else {
      $feeds = check_plain($feeds[0]['value']);
      $feeds_array = explode(' ', $feeds);
      $feeds = str_replace(' ', ' OR ', $feeds);
      $search = $feeds;
    }
  }
  
  if(!$tweets) {
    $accounts = twitter_load_authenticated_accounts();
    $account = array_shift($accounts);
    
    $twitter = twitter_connect($account);
    $params['q'] = $search;
    $tweets = $twitter->call('search/tweets', $params);
  }
  
  if($node) {
    $record = array(
        'nid' => $node->nid,
        'updated' => time(),
        'data' => $tweets,
    );
    drupal_write_record('multistream_twitter_feeds', $record, $update ? 'nid' : null);
  }  
  //$tweets = $twitter->search_tweets($search, array('include_entities'=>'true'));
  $output .= '<div id="twitter-feed">';
  foreach($tweets['statuses'] as $tweet) {
    $tweet['twitter_id'] = $tweet['id'];
    
    // Format the timestamp.
    $time_diff = REQUEST_TIME - strtotime($tweet['created_at']);
    
    // Format the message.  
    $tweet['time_ago'] = t('%time ago', array('%time' => format_interval($time_diff, 2))); 
    $vars['status'] = (object)$tweet;
    $vars['author'] = (object)$tweet['user'];
    $output .= theme('twitter_status', $vars);
  }
  $output .= '</div>';
  
  //return $output;
  $hashtags = array();
  foreach($feeds_array as $item) {
    if(strpos($item, '#') !== false) {
      $hashtags[] = str_replace('#', '', $item);      
    } elseif(strpos($item, '@') !== false) {
      $users[] = $item;
    }
  }
  
  $hash = '';
  if(!empty($hashtags)) {
    $hash = implode(',', $hashtags);
  }
  $via = '';
  if(!empty($users)) {
    $via = implode(' ', $users);
  }
    
  $output .= '<a href="https://twitter.com/intent/tweet?hashtags='.$hash.'&text='.$via.'">Send a Tweet</a>';
  
  $output .= '' . //'<a class="twitter-timeline"  href="https://twitter.com/search?q='.$search.'" data-widget-id="">Tweets</a>'.
    '<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>';
    
  return $output;
}

function multistream_form_new_multistream($form, $form_state, $save = false) {
  // are we in an existing node?
  if(arg(0) == 'node') {
    $node = menu_get_object();
  }

  $form_id = $save ? 'multistream-form-new-multistream-save' : 'multistream-form-new-multistream-new';
  $form['#id'] = $form_id;
  $form['#prefix'] = '<div id="'.$form_id.'-wrapper">';
  $form['#suffix'] = '</div>';
  
  
  if(!$save) {    
    $form['message'] = array(
      '#markup' => '<strong>New Multi-Stream</strong><p class="multistream-updated"><small>Creating a new multi-stream will clear the player stage.<br/><br/>Would you like to save your Now Playing first?</small></p>',
    );
  } else {
    $form['message'] = array(
        '#markup' => '<strong>Save to Favorites</strong><p class="multistream-updated"><small>Add a title and save.</small></p>',
    );    
  }

  $form['title'] = array(
    '#type' => 'textfield',
    '#size' => 30,
    //'#title' => t('Save Multi-Stream'),
    //'#prefix' => '<strong>New Multi-Stream</strong><br/><small>Creating a new multi-stream will clear the player stage.</small>',
    '#suffix' => '',    
    '#attributes' => array('placeholder'=>'Enter Multi-Stream Title'),
  );
  
  $submit_id = $save ? 'save-multistream-button-save' : 'save-multistream-button-new';

  $form['submit'] = array(
  	'#type' => 'submit',
    '#id' => $submit_id,
    '#value' => t('Save'),
    '#prefix' => '',
    '#validate' => array('multistream_form_new_multistream_validate'),
    '#ajax' => array(
        'callback' => 'multistream_form_new_multistream_callback',
        'wrapper' => $form_id.'-wrapper',
        'effect' => 'fade',
        'speed' => 'slow',
        'method' => 'replace',
    ),      
  );
  
  if(!$save) {
    $form['clear'] = array(
    	'#markup' => '<div class="clear-stage">'.l('No, clear player stage', 'multistream').'</div>',
    );
  }
  
  $form['streams'] = array('#type'=>'hidden');

  return $form;
}

function multistream_form_new_multistream_validate(&$form, &$form_state) {
  if(!$title = $form_state['values']['title']) {
    form_set_error('title', 'You must enter a title');
  }
}

function multistream_form_new_multistream_callback(&$form, &$form_state) {
  global $user;

  if(!$form_state['executed']) {
    return $form;
  }
  
  $title = $form_state['values']['title'];
  
  $node = new stdClass();
  $node->type = 'multistream';
  $node->title = $title;
  node_object_prepare($node);
  $node->language = 'und'; // Or e.g. 'en' if locale is enabled
  $node->uid = $user->uid;
  $node->status = 1; //(1 or 0): published or not
  $node->promote = 0; //(1 or 0): promoted to front page
  $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
  $node->is_new = true;
  
  foreach($form_state['values']['streams'] as $id => $stream_id) {
    $node->field_streams['und'][]['target_id'] = $id;
  }
  $node = node_submit($node);
  node_save($node);
}

function multistream_form_manage($node = null) {
  drupal_add_library('system', 'drupal.collapse');
  
  // required for the loaded form to be ajaxy
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_library('system', 'jquery.form');
    
	$riot = false;
	$nodes = sr_core_get_entities('multistream', 'owned');
	
	$output['multistreams']['#prefix'] = '<div id="multistream-manage">';
	$output['multistreams']['#suffix'] = '</div>';
	
	$output['multistreams']['select']['#markup'] = '<div id="manage-open">Open Multi-Stream</div>';
	$output['multistreams']['results'] = array(
	  '#prefix' => '<div id="manage-selection">',	    
	  '#markup' => drupal_render(node_view_multiple($nodes, 'selection')),
	  '#suffix' => '</div><div id="manage-form"></div>',
	);
	
	return $output;
	
	if(!$node) {
		// Are we in a node?		
		if(!$node = menu_get_object()) {
			//return;
		}
		
		if(isset($node->type) && $node->type == 'multistream') {
			$riot = true;
		}		
	} else {
		$riot = true;
	}
	
	$output['filter']['select'] = array(
		'#title' => t('Open & Customize'),
		'#type' => 'textfield',			
		'#autocomplete_path' => 'my-multistreams/autocomplete',
		'#id' => 'my-multistream-select',
	);
	
	$output['filter']['select_submit'] = array(
		'#type' => 'button',
		'#value' => t('Open'),
		'#id' => 'filter-manage-multistream',
		'#ajax' => array(
				'callback' => 'multistream_block_manage_filter_callback',
					'wrapper' => 'pager-content',
					'effect' => 'fade',
					'speed' => 'slow',
					'method' => 'append',
			),
			'#prefix' => '<div id="pager-content"></div>',
	);
	
	if($riot) {
		form_load_include($form_state, 'inc', 'node', 'node.pages');
		$node->is_manager = true;
		$output['node_edit'] = drupal_get_form('multistream_node_form', $node);
	}
	return $output;
}

function multistream_block_manage_filter_callback() {
	
}

function multistream_form_browse_by_game() {
	$form['keyword'] = array(
		'#type' => 'textfield',
		'#id' => 'browse-by-game',
	  '#size' => 25,
		//'#autocomplete_path' => 'game/autocomplete',	
		'#prefix' => '<small> '. t('Search game titles, channels or by keyword:') .'</small>',
	  '#attributes' => array('placeholder'=>'Enter Search'),
	);
	
	$form['search'] = array(
		'#type' => 'image_button',
    '#src' => drupal_get_path('module', 'multistream') . '/images/SearchSmLt.png',
    '#attributes' => array('alt'=>'Search'),	     
	  '#name' => 'browse-search-button',
		'#id' => 'browse-by-game-submit',			
		'#ajax' => array(
				'callback' => 'multistream_form_browse_by_game_callback',
				'wrapper' => 'browse-results',
				'effect' => 'fade',
				'speed' => 'slow',
				'method' => 'replace',
		),
		'#suffix' => '<div id="browse-filter-wrapper" class="filter-wrapper" style="display:none;"><div id="browse-filter-button" class="filter-button">Filter</div><div id="browse-filter-options-wrapper" class="filter-options-wrapper" style="display:none;"><div>Filter By:</div><ul id="browse-filter-options" class="filter-options"><li class="multistreams">Multistreams</li><li class="streams">Streams</li></ul></div></div>',
				
	);
	
	return $form;
}

function multistream_form_browse_by_game_callback($form, &$form_state) {
  $keyword = $form_state['values']['keyword'];
  $commands = array();
  
  // Execute multistream and streams browse
  $ms_view = views_get_view('browse_multistreams');
  $ms_view->set_display('block');
  $ms_view->set_arguments(array($keyword));
  // change the amount of items to show
  //$ms_view->set_items_per_page(4);
  $ms_view->pre_execute();
  $ms_view->execute();
  $ms_total = $ms_view->total_rows;
  
  $s_view = views_get_view('browse_streams');
  $s_view->set_display('block');
  $s_view->set_arguments(array($keyword));
  // change the amount of items to show
  //$ms_view->set_items_per_page(4);
  $s_view->pre_execute();
  $s_view->execute();
  $s_total = $s_view->total_rows;
    
  //return $ms_view->render();  
  $commands['filter'] = ajax_command_invoke('#browse-filter-wrapper', 'hide');
  // If only one has results don't show filter
  if(!$ms_total || !$s_total) {
    if($s_total) {
      $results = $s_view->render();
    } elseif($ms_total) {
      $results = $ms_total->render();
    } else {
      $delta = 'browse_no_results';
      $panel_mini = panels_mini_load($delta);
      
      //ctools_include('context');
      //$context = ctools_context_create('entity:node', $node);
      //$contexts = ctools_context_match_required_contexts($panel_mini->requiredcontexts, array($context));
      //$panel_mini->context = $panel_mini->display->context =  ctools_context_load_contexts($panel_mini, FALSE, $contexts);
      $panel_mini->display->css_id = panels_mini_get_id($panel_mini->name);
      
      // Here is the markup, to with with whatever you wish.
      $results = panels_render_display($panel_mini->display);        
    }
  } else {   
    $commands['filter'] = ajax_command_invoke('#browse-filter-wrapper', 'show');
    $results .= '<div id="browse-results-streams" class="results-streams">'.$s_view->render().'</div>';
    $results .= '<div id="browse-results-multistreams" style="display:none;" class="results-multistreams">'.$ms_view->render().'</div>';
  }
  
  //$output = '<div id="browse-results">';
  //$output .= $results;
  //$output .= '</div>';

  $commands[] = ajax_command_html('#browse-results', $results);
  //return $output;
  
  return array('#type'=>'ajax', '#commands'=>$commands);
}

function multistream_preprocess_multistream_now_playing(&$vars) {
//	debug($vars['elements']);
	
	//$vars['save_queue'] = '<a id="save-queue" href="#">Save Changes</a>';
	// Streams have been ordered already
	$streams = $vars['block']['#streams'];
	
	$vars['now_playing'] = array();
	$vars['queue'] = array();
		
	foreach($streams as $key => $stream) {
		if($key <= PLAYER_MAX_DEFAULT) {
		  $stream->stream_pos = $key;
		  //$controller = entity_get_controller('stream');
		  //$vars['now_playing'][] = $controller->view(array($stream));
		  //$vars['now_playing'][] = ->view(array($stream));
			$vars['now_playing'][] = entity_view('stream', array($stream));
		} else {
			$vars['queue'][] = entity_view('stream', array($stream));
		}
	}
}

function multistream_theme() {
	$return = array(
		'multistream_now_playing' => array(
				'arguments' => array('vars' => array()),
				'template' => 'multistream-now-playing',
				'path' => drupal_get_path('module', 'multistream').'/templates',
				'render element' => 'block',
		),	
		'multistream_view_multistream' => array(
				'arguments' => array('vars' => array()),
				'template' => 'multistream-view-multistream',
				'path' => drupal_get_path('module', 'multistream').'/templates',
				'render element' => 'element',
		),	
	  'node__multistream' => array(
	      'render_element' => 'content',
	      'base hook' => 'node',
	      'template' => 'node--multistream',
	      'path' => drupal_get_path('module', 'multistream') . '/templates',
		),
	  'page__multistream' =>  array(
	      'template' => 'page--multistream',
	      'path' => drupal_get_path('module', 'multistream') . '/templates',
	      'render element' => 'page'
	  ),	    
	);
	
	return $return;
}

function multistream_sort_riot_streams($nodes = array()) {
	$i = 0;

	//sort the streams so ones that are live are at top
	$sorting = array();

	foreach($nodes as $node) {
		$i++;
		$is_live = $node->is_live ? 1 : 0;
		$key = sprintf('%04d', $i);
		$title = $node->channel;
		if($is_live) {
			$sorting['live-'.$title.$key] = $node;
		} else {
			$sorting['notlive-'.$title.$key] = $node;
		}
	}

	ksort($sorting);

	$i = 0;

	$streams = array();
	foreach($sorting as $sort) {
		$i++;
		$streams[$i] = $sort;
	}

	return $streams;
}

function stream_load_stream_by_channel($channel) {
  $controller = new StreamController('stream');
  $streams = $controller->load(false, array('channel'=>$channel));
  if(empty($streams)) {
    return false;
  } 
  
  return array_shift($streams);
}

function stream_get_stream_settings($stream, $n) {

	$return = new stdClass;
	
	$return->position = $n;
	$return->stream_id = $stream->stream_id;
	$return->channel = $stream->channel;
	$return->provider = $stream->provider;
	
	//return $return;
	
	
	$provider = $stream->provider;
	$provider = taxonomy_term_load($provider);

	$field_player_url = field_get_items('taxonomy_term', $provider, 'field_player_source');
	$field_params 		= field_get_items('taxonomy_term', $provider, 'field_params');
	$field_vars 			= field_get_items('taxonomy_term', $provider, 'field_vars');
	$field_chat_url 	= field_get_items('taxonomy_term', $provider, 'field_chat_url');

	$player = $field_player_url[0]['value'];
	$player = str_replace('[stream:channel]', $stream->channel, $player);
	$chat = $field_chat_url[0]['value'];
	$chat = str_replace('[stream:channel]', $stream->channel, $chat);

	$return->src = $player;
	//$return->channel = $node->field_channel['und'][0]['value'];
	//->channel_name = $node->field_channel_name['und'][0]['value'];
	//$return->player_num = $n;
	//$return->stream_num = $n;
	//$return->stream_id = $node->nid;
	//$items = field_get_items('node', $node, 'field_current_viewers');
	//$return->num_viewers = $items ? $items[0] : 0;
	$return->chat = $chat;
	//$return->provider = strtolower($provider->name);

	$params = explode("\n", $field_params[0]['value']);
	$params = array_map('trim', $params);
	$params = array_filter($params, 'strlen');

	foreach ($params as $param) {
		if (strpos($param, '|') !== FALSE) {
			list($key, $value) = explode('|', $param);
			$theparams[$key] = (isset($value) && $value !=='') ? $value : $key;
			$theparams[$key] = token_replace($value, array('node' => $node));
		}
	}

	$key = '';
	$value = '';

	$vars = explode("\n", $field_vars[0]['value']);
	$vars = array_map('trim', $vars);
	$vars = array_filter($vars, 'strlen');
	$thevars[] = array();
	foreach ($vars as $var) {
		if (strpos($var, '|') !== FALSE) {
			list($key, $value) = explode('|', $var);
			$thevars[$key] = (isset($value) && $value !=='') ? $value : $key;
			$thevars[$key] = token_replace($value, array('node' => $node));
		}
	}

	global $base_root;
	if($base_root == 'http://localhost.gvod') {
		$thevars['consumer_key'] = '';
	}
	$return->base_root = $base_root;

	$vars = "?1=1";
	foreach($thevars as $key => $value) {
		$vars .= "&".$key.'='.$value;
	}
	$return->vars = $thevars;
	$return->name = 'riot-player';

	return $return;
}

function multistream_preprocess_node(&$vars) {
  global $user;
  
  $node = $vars['node'];

  if($node->type != 'multistream') {
    return;
  }
  
  if($node->uid == $user->uid) {
    $vars['classes_array'][] = 'multistream-owner';    
  }
  $vars['classes_array'][] = $vars['view_mode'];
  
  $vars['attributes_array']['data-nid'][] = $node->nid;
}

function multistream_node_view($node, $view_mode) {	
	global $user;
	
  if($node->type != 'multistream') {
		return;
	}

	if(!$items = field_get_items('node', $node, 'field_streams')) {
	  $items = array();
	}
	
	$streams = array();
	
	foreach($items as $item) {
	  $streams[] = $item['target_id'];
	}
	
	$streams = entity_load('stream', $streams);
  $live = 0;
  $total = count($streams);
  
	foreach($streams as $stream) {
	  if($stream->is_live) {
	    $live++;
	  }
	}

	if($view_mode == 'teaser') {
	  $thumb = field_view_field('node', $node, 'field_cover', 'teaser');
	  //$node->content['thumb'] = $thumb;
	}
	
	if($view_mode != 'full') {
	  $node->content['title'] = array('#markup' => l($node->title, 'node/'.$node->nid));	   
	  //$node->content['title'] = array('#markup' => '<div class="title">'.l($node->title, 'node/'.$node->nid).'</div>');
	  $node->content['streams'] = array('#markup' => '<div class="live">'.t('@live live of @total streams', array('@live'=>$live, '@total'=>$total)).'</div>');
	}
	
	if($view_mode == 'selection') {
	  return;
	}	
	
	if($view_mode == 'full') {
	  unset($node->content['field_player_background']);
	  
	  $node->content['multistream']['#markup'] = multistream_view_multistream('riot', $streams, $node);	   
	  $settings['multistream']['is_owner'] = false;
	  
	  if($user->uid == $node->uid) {
	    $settings['multistream']['is_owner'] = true;
	    $settings['multistream']['nid'] = $node->nid;
	  
	  }
	  
	  drupal_add_js($settings, 'setting', 'footer', false, true, false);	  
	}

}

function multistream_autocomplete_my_multistreams() {
	global $user;
	
	$results = db_select('node', 'n')
		->fields('n', array('nid', 'title'))
		->condition('n.uid', $user->uid)
		->orderBy('n.title', 'ASC')
		->range(0, 10)
		->execute()
		->fetchAllKeyed();	

	//dpm($results);
	//return;
	foreach($results as $nid => $title) {
		$matches[$title] = $title;
	}
	
	drupal_json_output($matches);
}

function multistream_autocomplete_stream($keyword) {  
  $keyword .= '%';
  $sql = "SELECT channel FROM {stream} WHERE channel LIKE(:search) ORDER BY channel ASC LIMIT 10";
  $results = db_query($sql, array(':search'=>$keyword))->fetchAllKeyed(0,0);
  $matches = array();

  foreach($results as $item) {
    $matches[$item] = $item;
  }
  drupal_json_output($matches);
}

function multistream_autocomplete_game() {
	// If the request has a '/' in the search text, then the menu system will have
	// split it into multiple arguments, recover the intended $tags_typed.
	$args = func_get_args();

	$tags_typed = implode('/', $args);

	$field_name = 'field_stream_category';
	// Make sure the field exists and is a taxonomy field.
	if (!($field = field_info_field($field_name)) || $field['type'] !== 'taxonomy_term_reference') {
		// Error string. The JavaScript handler will realize this is not JSON and
		// will display it as debugging information.
		print t('Taxonomy field @field_name not found.', array('@field_name' => $field_name));
		exit;
	}

	// The user enters a comma-separated list of tags. We only autocomplete the last tag.
	$tags_typed = drupal_explode_tags($tags_typed);
	$tag_last = drupal_strtolower(array_pop($tags_typed));

	$term_matches = array();
	if ($tag_last != '') {

		// Part of the criteria for the query come from the field's own settings.
		$vids = array();
		$vocabularies = taxonomy_vocabulary_get_names();
		foreach ($field['settings']['allowed_values'] as $tree) {
			$vids[] = $vocabularies[$tree['vocabulary']]->vid;
		}

		$query = db_select('taxonomy_term_data', 't');
		$query->addTag('translatable');
		$query->addTag('term_access');

		// Do not select already entered terms.
		if (!empty($tags_typed)) {
			$query->condition('t.name', $tags_typed, 'NOT IN');
		}
		// Select rows that match by term name.
		$tags_return = $query
		->fields('t', array('tid', 'name'))
		->condition('t.vid', $vids)
		->condition('t.name', '' . db_like($tag_last) . '%', 'LIKE')
		->range(0, 10)
		->execute()
		->fetchAllKeyed();

		$prefix = count($tags_typed) ? drupal_implode_tags($tags_typed) . ', ' : '';

		foreach ($tags_return as $tid => $name) {
			$n = $name;
			// Term names containing commas or quotes must be wrapped in quotes.
			if (strpos($name, ',') !== FALSE || strpos($name, '"') !== FALSE) {
				$n = '"' . str_replace('"', '""', $name) . '"';
			}
			$term_matches[$prefix . $n] = check_plain($name);
			//$term = taxonomy_term_load($tid);
			//$term_matches[$prefix . $n] = drupal_render(entity_view('taxonomy_term', array($term), 'teaser_sm'));
		}
	}

	drupal_json_output($term_matches);
}

function multistream_form_riot_node_form_alter(&$form, &$form_state) {
	$node = $form['#node'];
	if(!isset($node->type) && $node->type != 'multistream') {
		return;
	}

	//don't add ['streams'] if we're not in the manager
	//otherwise it'll screw up regular node edit form
	if(!isset($node->is_manager)) {
		return;
	}

	$values = isset($form_state['input']) ? $form_state['input'] : null;
	$form['streams']['#tree'] = true;
	if($values && !empty($values['streams'])) {
		$streams = is_array($values['streams']) ? $values['streams'] : array();

		foreach($streams as $key => $value) {
			$form['streams'][$key] = array('#type'=>'hidden','#value'=>$value);
		}

	} else {

		if(!$items = field_get_items('node', $node, 'field_streams')) {
			$items = array();
		}
		foreach($items as $key => $value) {
			$form['streams'][$value['target_id']] = array('#type'=>'hidden','#value'=>$value['target_id']);
		}
	}

	if($node) {
		$form['riot_nid'] = array(
				'#type' => 'hidden',
				'#value' => $node->nid,
				'#id' => 'riot_nid',
		);
	}

	$form['#theme'] = 'multistream_form_node';
	$form['actions']['submit']['#id'] = 'riot-manage-submit';
	$form['#id'] = 'riot-edit-form';
}

function multistream_form_add_channel($form, $form_state) {
	$form['#ajax']['enabled'] = true;
	//$message = variable_get('multistream_add_channel_message', 'Added channel');
	
	//$form['success']['#markup'] = $message;
	$form['channel'] = array(
			'#type' => 'textfield',
			'#prefix' => '<small>'.t('Add Twitch Channels by name; add multiple channels by entering a space between each channel.').'</small>',
	    '#id' => 'add-channel',
	    '#size' => 20,
	);

	$form['channel_add'] = array(
			'#type' => 'image_button',
	    '#src' => drupal_get_path('module', 'multistream') . '/images/AddChannelSmLt.png',
	    '#attributes' => array('alt'=>'Add Channel'),
			'#name' => 'channel_add',
			'#id' => 'add-channel-submit',
			'#validate' => array('multistream_block_add_channel_validate'),
			'#submit' => array('multistream_block_add_channel_submit'),
			'#ajax' => array(
					'callback' => 'multistream_block_add_channel_callback',
					'wrapper' => 'add-channel-message',
					'effect' => 'fade',
					'speed' => 'slow',
					'method' => 'append',
			),
			//'#suffix' => '<div id="add-channel-message"></div>',
	);
	
	$form['wrapper']['#markup'] = '<div id="add-channel-message"></div>';
	

	//$form['#theme'] = 'multistream_block_add_channel';

	return $form;
}

function multistream_preprocess_page($vars, $hook) {
  $test = 'test';
  
  if(!isset($vars['node'])) {
    return;
  }
  
  $node = $vars['node'];
  
  if($node->type != 'multistream') {
    return;
  }
  
  $vars['theme_hook_suggestions'][] = 'page__multistream';
}

function multistream_block_view_quicktabs_player_menu_alter(&$data, $block) {
  foreach($data['content']['content']['tabs']['tablinks'] as $key => $tab) {
    $data['content']['content']['tabs']['tablinks'][$key]['#attributes']['class'][] = drupal_html_class($tab['#title']);
  }
}

function multistream_block_view_quicktabs_social_menu_alter(&$data, $block) {
  foreach($data['content']['content']['tabs']['tablinks'] as $key => $tab) {
    $data['content']['content']['tabs']['tablinks'][$key]['#attributes']['class'][] = drupal_html_class($tab['#title']);
  }
}

function multistream_form_multistream_node_form_alter(&$form, &$form_state) {
  $node = $form['#node'];
  $stream_nids = array();
    
  foreach($form['field_streams']['und'] as $key => $stream) {
    if(!is_numeric($key)) {
      continue;
    }
    if (preg_match("/.+\((\d+)\)/", $stream['target_id']['#default_value'], $matches)) {
      $id = $matches[1];
      $stream_nids[$id] = $id;
      $form['field_streams']['und'][$key]['target_id']['#attributes']['data-id'][] = $id;
    }
  }
  
  if(!isset($node->is_manage_form)) {
    return;
  }
  
  $form['changed']['#default_value'] = time() + 300; // gives the user 5 minutes to modify this form
  
  // Add autocomplete to add new streams
  $form['add_stream'] = array(
  	'#type' => 'textfield',
    '#title' => t('Add Channel'),
    '#size' => 10,
    '#autocomplete_path' => 'multistream/stream-autocomplete',
    '#weight' => -10,
  );
  
  $form['add_stream_submit'] = array(
  	'#type' => 'button',
    '#value' => t('Add'),
    '#ajax' => array(
  	 'callback' => 'multistream_ajax_add_stream_submit_callback',
    ),
  );
  $form['#group_children']['add_stream'] = 'group_streams';
  $form['#group_children']['add_stream_submit'] = 'group_streams';
  

  $streams = entity_load('stream', $stream_nids, true);
  
  foreach($form['field_streams']['und'] as $key => $stream) {
    if(!is_numeric($key)) {
      continue;
    }
    if(!isset($stream['target_id']['#attributes']['data-id'])) {
      continue;
    }
    $form['field_streams']['und'][$key]['_weight']['#type'] = 'textfield';
    
    $id = $stream['target_id']['#attributes']['data-id'][0];
    $form['field_streams']['teasers'][$key] = array(
    	'#type' => 'markup',
      '#markup' => drupal_render(entity_view('stream', array($streams[$id]), 'teaser'))
    );
  }  
  
  $form['field_website']['und'][0]['url']['#size'] = 6;
  
  // Make socials disabled by default
  $form['field_twitter']['#attributes']['class'][] = 'noclick';
  $form['field_facebook']['#attributes']['class'][] = 'noclick';
  $form['field_reddit']['#attributes']['class'][] = 'noclick';
  $form['field_website']['#attributes']['class'][] = 'noclick';
  $form['field_google_plus']['#attributes']['class'][] = 'noclick';
  $form['field_youtube']['#attributes']['class'][] = 'noclick';
  $form['field_twitter_feed']['#attributes']['class'][] = 'noclick';
  
  
  // Edit buttons
  $form['field_twitter']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  $form['field_facebook']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  $form['field_reddit']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  $form['field_website']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  $form['field_google_plus']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  $form['field_youtube']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  $form['field_twitter_feed']['und'][0]['#suffix'] = '<div class="btn connect">Edit</div>';
  
  $form['field_twitter_feed']['#prefix'] = '<h2>Twitter Feed</h2><small>Viewers can reply, retweet and favorite your tweets directly from StreamRiot. Add friends and hashtags too!</small>';
  
  $form['actions']['submit']['#id'] = 'manage-form-submit';
  $form['actions']['submit']['#name'] = 'manage-form-submit';
  
  $form['actions']['submit']['#ajax'] = array(
      'event' => 'click',
      'callback' => 'multistream_ajax_manage_form_submit',
      'wrapper' => 'manage-form',
      'method' => 'html',
      'effect' => 'fade',
  ); 

  // Move delete to more settings
  $form['delete'] = $form['actions']['delete'];
  unset($form['actions']['delete']);
  
  $form['delete']['#ajax'] = array(
      'event' => 'click',
      'callback' => 'multistream_ajax_manage_delete_callback',
      'wrapper' => 'manage-form',
      'method' => 'html',
      'effect' => 'fade',
  );  
  $form['#group_children']['delete'] = 'group_settings';
  
}

function multistream_ajax_manage_form($nid) {
  $node = node_load($nid);
  
  if($node->type != 'multistream') {
    return false;
    exit;
  }
  
  if(!node_access('update', $node)) {
    return false;
    exit;
  }
  
  form_load_include($form_state, 'inc', 'node', 'node.pages');
  
  $node->is_manage_form = true;
  
  $form = drupal_get_form('multistream_node_form', $node);
  

  
  $form = drupal_render($form);
  
  // Generate the settings:
  $settings = FALSE;
  $javascript = drupal_add_js(NULL, NULL);
  if(isset($javascript['settings'], $javascript['settings']['data']))
  {
    $settings = '<script type="text/javascript">jQuery.extend(Drupal.settings, ';
    $settings .= drupal_json_encode(call_user_func_array('array_merge_recursive', $javascript['settings']['data']));
    $settings .=  ');</script>';
  }
  
  die($form . $settings);

}

function multistream_ajax_manage_form_submit($form, &$form_state) {
  $form = drupal_rebuild_form($form['#form_id'], $form_state, $form);
  return $form;
}


function multistream_ajax_manage_delete_callback($form, &$form_state) {
  // Make sure the user has permission
  $node = $form['#node'];
  
  if(!node_access('update', $node)) {
    return;
  }
  
  // Delete the node
  node_delete($node->nid);
  
  // Send a command that refreshes all drop downs
  $commands[] = ajax_command_remove('.node-multistream[data-nid="'.$node->nid.'"]');
  // Close the manager
  $commands[] = ajax_command_html('#manage-form', '');
  
  return array('#type'=>'ajax', '#commands'=>$commands);
}

function multistream_ajax_favorites() {
  $commands = array();
  
  // Execute multistream and streams browse
  $ms_view = views_get_view('favorite_multistreams');
  $ms_view->set_display('block');
  $ms_view->set_arguments(array($keyword));
  // change the amount of items to show
  //$ms_view->set_items_per_page(4);
  $ms_view->pre_execute();
  $ms_view->execute();
  $ms_total = $ms_view->total_rows;
  
  $s_view = views_get_view('favorite_streams');
  $s_view->set_display('block');
  $s_view->set_arguments(array($keyword));


  $s_view->pre_execute();
  $s_view->execute();
  $s_total = $s_view->total_rows;
  
  //return $ms_view->render();
  //$commands['filter'] = ajax_command_invoke('#favorites-filter-wrapper', 'hide');
  $results = '';
  // If only one has results don't show filter
  if(!$ms_total || !$s_total) {
    if($s_total) {
      $results = $s_view->render();
    } elseif($ms_total) {
      $results = $ms_total->render();
    } else {
      exit;
    }
  } else {
    $filter = '<div id="favorites-filter-wrapper" class="filter-wrapper"><div id="favorites-filter-button" class="filter-button">Filter</div><div id="favorites-filter-options-wrapper" class="filter-options-wrapper" style="display:none;"><div>Filter By:</div><ul id="browse-filter-options" class="filter-options"><li class="multistreams">Multistreams</li><li class="streams">Streams</li></ul></div></div>';
  
    //$commands['filter'] = ajax_command_invoke('#favorites-filter-wrapper', 'show');
    $results .= $filter;
    $results .= '<div id="favorites-results-streams" class="results-streams">'.$s_view->render().'</div>';
    $results .= '<div id="favorites-results-multistreams" class="results-multistreams" style="display:none;">'.$ms_view->render().'</div>';
  }

  
  $commands[] = ajax_command_html('#favorites-empty', $results);
  //return $output;
  
  ajax_deliver(array('#type'=>'ajax', '#commands'=>$commands));
  exit;  
}

function multistream_block_add_channel_validate($form, &$form_state) {
  
}

function multistream_block_add_channel_submit($form, &$form_state) {


}

function multistream_block_add_channel_callback($form, &$form_state) {
  $channels = $form_state['values']['channel'];
  $channels = trim($channels);
  $channels = explode(' ', $channels);
  $found = false;
  
  foreach($channels as $channel) {
    if(!$stream = stream_import_twitch_stream($channel)) {
      continue;
    }
    $found = true;
        
    $settings['multistream']['streams'][$stream->stream_id] = stream_get_stream_settings($stream, 'q');
    
    $commands[] = ajax_command_settings($settings);
    $stream_render = drupal_render(entity_view('stream', array($stream)));
    $commands[] = ajax_command_invoke('#queue', 'srInsertStream', array($stream_render, $stream->stream_id, 'q'));
    
  }
  $commands[] = ajax_command_invoke('#add-channel-message', 'addClass', array('messages'));
  if(!$found) {
    $commands[] = ajax_command_html('#add-channel-message', 'Channel not found');
    $commands[] = ajax_command_invoke('#add-channel-message', 'addClass', array('error'));
    $commands[] = ajax_command_invoke('#add-channel-message', 'removeClass', array('status'));    
  } else {
    $commands[] = ajax_command_html('#add-channel-message', 'Channel(s) added');
    $commands[] = ajax_command_invoke('#add-channel-message', 'addClass', array('status'));
    $commands[] = ajax_command_invoke('#add-channel-message', 'removeClass', array('error'));            
  }
  
  
  return array('#type'=>'ajax', '#commands'=> $commands);
}

function multistream_ajax_add_stream_submit_callback(&$form, &$form_state) {
  $channel = $form_state['values']['add_stream'];
  
  if($stream = stream_load_stream_by_channel($channel)) {
    $teaser = entity_view('stream', array($stream));
    $commands[] = ajax_command_invoke('div[id*="edit-field-streams"] .stream-wrapper[data-id="'.$stream->stream_id.'"]', 'remove');
    $commands[] = ajax_command_prepend('div[id*="edit-field-streams"]', drupal_render($teaser));
    $commands[] = ajax_command_invoke('div[id*="field-streams-add-more-wrapper"] .field-multiple-table tbody tr:last input.form-autocomplete', 'attr', array('value', $channel .' ('.$stream->stream_id.')'));
    $commands[] = ajax_command_invoke('input[name="field_streams_add_more"]', 'trigger', array('mousedown'));
  }
  
  return array('#type'=>'ajax', '#commands'=>$commands);
}